service: serverless-reason-poc

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  hello:
    handler: src/Main.hello
  now:
    handler: src/OrderHistory.now
  orderHistory:
    handler: src/OrderHistory.orderHistory
