// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Knex = require("knex");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function toOption(prim) {
  if (prim == null) {
    return undefined;
  } else {
    return Js_primitive.some(prim);
  }
}

var connection = {
  host: process.env.DATABASE_HOST,
  port: process.env.DATABASE_PORT,
  user: process.env.DATABASE_USERNAME,
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_NAME
};

var pool = {
  min: 0,
  max: 5,
  idleTimeoutMillis: 1000
};

var config = {
  client: "pg",
  connection: connection,
  pool: pool,
  acquireConnectionTimeout: 2000
};

var knex = Knex(config);

var getWithDefault = Js_option.getWithDefault;

exports.toOption = toOption;
exports.getWithDefault = getWithDefault;
exports.connection = connection;
exports.pool = pool;
exports.config = config;
exports.knex = knex;
/* connection Not a pure module */
