// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function hello($$event, _context, callback) {
  var match = $$event.queryStringParameters;
  var message;
  if (match == null) {
    message = "";
  } else {
    var match$1 = match.name;
    message = (match$1 == null) ? "Hello from Reason!" : "Hello " + match$1;
  }
  var body = {
    message: message,
    event: $$event
  };
  var response = {
    statusCode: 200,
    body: JSON.stringify(body)
  };
  return callback(null, response);
}

exports.hello = hello;
/* No side effect */
